services:
  server:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - GIN_MODE=debug
      - DB_NAME=Dev
    restart: "no"

  frontend_mobile:
    build:
      context: ./frontend/mobile
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/mobile/.env
    environment:
      - NODE_ENV=production
    restart: "no"

  frontend_web:
    build:
      context: ./frontend/web
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    restart: "no"
