// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/applet": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve all applets associated with the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applets"
                ],
                "summary": "Get all applets for the user",
                "responses": {
                    "200": {
                        "description": "List of user applets",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Applet"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new applet for the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applets"
                ],
                "summary": "Add a new applet",
                "parameters": [
                    {
                        "description": "Applet data",
                        "name": "applet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddApplet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update a applet for the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applets"
                ],
                "summary": "Update a new applet",
                "parameters": [
                    {
                        "description": "Applet data",
                        "name": "applet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateApplet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/github": {
            "get": {
                "description": "Handles Github login callback and issues a token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "github"
                ],
                "summary": "Github login callback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/github/login": {
            "get": {
                "description": "Initiates Github OAuth login process",
                "tags": [
                    "github"
                ],
                "summary": "Redirect to Github OAuth login",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/google": {
            "get": {
                "description": "Handles Google login callback and issues a token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google"
                ],
                "summary": "Google login callback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/google/login": {
            "get": {
                "description": "Initiates Google OAuth login process",
                "tags": [
                    "google"
                ],
                "summary": "Redirect to Google OAuth login",
                "responses": {
                    "302": {
                        "description": "Redirect"
                    }
                }
            }
        },
        "/microsoft": {
            "get": {
                "description": "Handles Azure login callback and issues a token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "microsoft"
                ],
                "summary": "Azure login callback",
                "responses": {
                    "200": {
                        "description": "Token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/microsoft/login": {
            "get": {
                "description": "Initiates Azure OAuth login process",
                "tags": [
                    "microsoft"
                ],
                "summary": "Redirect to Azure OAuth login",
                "responses": {
                    "302": {
                        "description": "Redirect"
                    }
                }
            }
        },
        "/services": {
            "get": {
                "description": "Get available services",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Get available services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ServiceAvailable"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/spotify": {
            "get": {
                "description": "Handles Spotify login callback and issues a token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spotify"
                ],
                "summary": "Spotify login callback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/spotify/login": {
            "get": {
                "description": "Initiates Spotify OAuth login process",
                "tags": [
                    "spotify"
                ],
                "summary": "Redirect to Spotify OAuth login",
                "responses": {
                    "302": {
                        "description": "Redirect"
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get user information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get user information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Login a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Login a user",
                "parameters": [
                    {
                        "description": "User object",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Register a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User object",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/youtube": {
            "get": {
                "description": "Handles Youtube login callback and retrieves latest liked videos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "youtube"
                ],
                "summary": "Youtube login callback",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/youtube/login": {
            "get": {
                "description": "Initiates Youtube OAuth login process",
                "tags": [
                    "youtube"
                ],
                "summary": "Redirect to Youtube OAuth login",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddApplet": {
            "type": "object",
            "properties": {
                "if": {
                    "type": "string"
                },
                "ifType": {
                    "type": "string"
                },
                "isOn": {
                    "type": "boolean"
                },
                "that": {
                    "type": "string"
                },
                "thatType": {
                    "type": "string"
                }
            }
        },
        "models.Applet": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "id_User": {
                    "type": "string"
                },
                "if": {
                    "type": "string"
                },
                "ifType": {
                    "type": "string"
                },
                "isOn": {
                    "type": "boolean"
                },
                "that": {
                    "type": "string"
                },
                "thatType": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.IfThat": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "prettyName": {
                    "type": "string"
                },
                "tokenName": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "urlLogin": {
                    "type": "string"
                }
            }
        },
        "models.ServiceAvailable": {
            "type": "object",
            "properties": {
                "if": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IfThat"
                    }
                },
                "that": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IfThat"
                    }
                }
            }
        },
        "models.UpdateApplet": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "if": {
                    "type": "string"
                },
                "ifType": {
                    "type": "string"
                },
                "isOn": {
                    "type": "boolean"
                },
                "that": {
                    "type": "string"
                },
                "thatType": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
